"""SCML 2026 participant team_21089 (agent id 21089, class AssariAsari).

Generated by scmlweb/python/update_agents_repo.py.
"""
from .strategy import AssariAsari as MAIN_AGENT

__all__ = ["MAIN_AGENT"]

# --- BEGIN generated metadata (scmlweb update_agents_repo.py) ---
ID = 21089
NAME = 'AssariAsari'
CLASS_NAME = 'AssariAsari'
VERSION = '3.11.15'
TEAM = 'Team 376'
AUTHOR = 'Rinon Asanuma'
MEMBERS = [{'name': 'Rinon Asanuma', 'institution': None, 'country': 'Japan'}]
COUNTRY = 'Japan'
INSTITUTION = 'Tokyo University of Agriculture and Technology'
TAGS = ['Search Algorithms', 'Heuristic / Rule-based', 'Optimization']
USES_LLM = False
DESC = "AssariAsari is a synchronous negotiation agent designed for the ANAC 2026 SCML OneShot league. Instead of optimizing each negotiation independently, it employs a compact, need-driven strategy that prioritizes aggregate quantity matching across all concurrent negotiations. It calculates proposals by distributing current supply and sales needs among active partners using mild capacity-based weights. For pricing, the agent utilizes a time-dependent concession function, conceding towards the opponent's limits as the deadline approaches. The core of its strategy lies in evaluating incoming offers as subsets rather than individually. It accepts groups of offers whose combined quantity best fits the aggregate need, explicitly penalizing surplus to avoid costly over-commitments. Furthermore, AssariAsari applies simple risk controls, including an adaptive quantity slack that increases near the deadline and a lightweight reliability estimate to prefer historically successful partners."
METADATA = {
    'id': ID, 'name': NAME, 'class_name': CLASS_NAME,
    'version': VERSION, 'team': TEAM, 'author': AUTHOR,
    'members': MEMBERS, 'country': COUNTRY,
    'institution': INSTITUTION, 'tags': TAGS,
    'uses_llm': USES_LLM, 'description': DESC,
}
# --- END generated metadata ---
