"""SCML 2026 participant team_21244 (agent id 21244, class Agent03Agent).

Generated by scmlweb/python/update_agents_repo.py.
"""
from .agent03.core.agent import Agent03Agent as MAIN_AGENT

__all__ = ["MAIN_AGENT"]

# --- BEGIN generated metadata (scmlweb update_agents_repo.py) ---
ID = 21244
NAME = 'agent03'
CLASS_NAME = 'Agent03Agent'
VERSION = '3.11.8'
TEAM = 'Team 403'
AUTHOR = 'Yifan Zhang'
MEMBERS = [{'name': 'Yifan Zhang', 'institution': 'South China University of Technology', 'country': 'China'}]
COUNTRY = 'China'
INSTITUTION = 'South China University of Technology'
TAGS = []
USES_LLM = False
DESC = ''
METADATA = {
    'id': ID, 'name': NAME, 'class_name': CLASS_NAME,
    'version': VERSION, 'team': TEAM, 'author': AUTHOR,
    'members': MEMBERS, 'country': COUNTRY,
    'institution': INSTITUTION, 'tags': TAGS,
    'uses_llm': USES_LLM, 'description': DESC,
}
# --- END generated metadata ---
