"""SCML 2026 participant team_21804 (agent id 21804, class OneshotOmegaNegotiator).

Generated by scmlweb/python/update_agents_repo.py.
"""
from .oneshot_agent.entry import OneshotOmegaNegotiator as MAIN_AGENT

__all__ = ["MAIN_AGENT"]

# --- BEGIN generated metadata (scmlweb update_agents_repo.py) ---
ID = 21804
NAME = 'CodexAgentOneshot'
CLASS_NAME = 'OneshotOmegaNegotiator'
VERSION = '2.1.0'
TEAM = 'Team 507'
AUTHOR = 'Ryota GENSEKI'
MEMBERS = [{'name': 'Ryota GENSEKI', 'institution': 'Tokyo University of Agriculture and Technology', 'country': 'Japan'}]
COUNTRY = 'Japan'
INSTITUTION = 'Tokyo University of Agriculture and Technology'
TAGS = []
USES_LLM = False
DESC = 'OneshotOmegaNegotiator is a synchronous portfolio-based negotiation agent for the SCML 2026 OneShot track. It evaluates concurrent offers jointly instead of treating each bilateral negotiation independently. Candidate bundles are ranked using an 85/15 quantity-price score, with official SCML utility, shortfall, and bundle size used as tie-breakers. The agent performs exact subset search for at most ten partners and switches to bounded beam search in larger markets to avoid exponential runtime. It distributes target quantities nearly equally, applies a small buyer-side fulfillment buffer, and dynamically raises the default per-partner quantity cap only when scarce active partners cannot collectively cover the remaining need. Counteroffers use deterministic utility-based reservation prices, public trading information, and partner-specific price and concession statistics. Bayesian success and failure estimates support partner selection. This design improves buyer fulfillment under strong opponents while preserving established seller and large-market behavior.'
METADATA = {
    'id': ID, 'name': NAME, 'class_name': CLASS_NAME,
    'version': VERSION, 'team': TEAM, 'author': AUTHOR,
    'members': MEMBERS, 'country': COUNTRY,
    'institution': INSTITUTION, 'tags': TAGS,
    'uses_llm': USES_LLM, 'description': DESC,
}
# --- END generated metadata ---
