"""SCML 2026 participant team_21637 (agent id 21637, class BayesianAgent).

Generated by scmlweb/python/update_agents_repo.py.
"""
from .bayesian_agent import BayesianAgent as MAIN_AGENT

__all__ = ["MAIN_AGENT"]

# --- BEGIN generated metadata (scmlweb update_agents_repo.py) ---
ID = 21637
NAME = 'BayesianAgent'
CLASS_NAME = 'BayesianAgent'
VERSION = '1.0.0'
TEAM = 'Team 371'
AUTHOR = 'kouta miyamoto'
MEMBERS = [{'name': 'kouta miyamoto', 'institution': 'Kyoto University', 'country': 'Japan'}]
COUNTRY = 'Japan'
INSTITUTION = 'Kyoto University'
TAGS = ['Bayesian Methods', 'Heuristic / Rule-based']
USES_LLM = False
DESC = 'BayesianAgent is a synchronous one-shot negotiator that combines Bayesian opponent classification with conservative quantity control. It probes early offers using alternating favorable and unfavorable prices to identify Greedy partners, then allocates quantities according to estimated acceptance rates. The agent accepts exact or near-complete subsets, prioritizes profitable partial agreements, and counters only for the remaining need. Seller-side responses avoid over-commitment and shortfall, while buyer-side offers are capped to reduce excess inventory. Target partner counts are smoothed from observed success rates, using ceil-based safety rounding to prevent oversized offers. Classification evidence is updated from first-offer outcomes, counters, and agreement results throughout the day.'
METADATA = {
    'id': ID, 'name': NAME, 'class_name': CLASS_NAME,
    'version': VERSION, 'team': TEAM, 'author': AUTHOR,
    'members': MEMBERS, 'country': COUNTRY,
    'institution': INSTITUTION, 'tags': TAGS,
    'uses_llm': USES_LLM, 'description': DESC,
}
# --- END generated metadata ---
