"""SCML 2026 participant team_21798 (agent id 21798, class Oneshot).

Generated by scmlweb/python/update_agents_repo.py.
"""
from .hi.oneshot import Oneshot as MAIN_AGENT

__all__ = ["MAIN_AGENT"]

# --- BEGIN generated metadata (scmlweb update_agents_repo.py) ---
ID = 21798
NAME = 'heyoneshot'
CLASS_NAME = 'Oneshot'
VERSION = '0.13.17'
TEAM = 'チーム298'
AUTHOR = 'カズマ'
MEMBERS = [{'name': '望月和真', 'institution': None, 'country': None}, {'name': 'カズマ', 'institution': 'Tokyo University of Agriculture and Technology', 'country': 'Japan'}]
COUNTRY = 'Japan'
INSTITUTION = 'Tokyo University of Agriculture and Technology'
TAGS = []
USES_LLM = False
DESC = 'The Oneshot agent is an advanced strategy built for the SCML OneShot track. During the early stages of the game, it distributes orders broadly—often slightly over-ordering—to gauge market responsiveness. Once the simulation passes its midpoint, the agent adopts a strictly cautious approach: it permanently abandons unreliable or bankrupt partners and concentrates its bulk orders solely on its most trusted, high-volume trading partner. To guarantee computational stability and eliminate timeout errors in large environments, Oneshot implements a hybrid resolution algorithm. It utilizes a precise full-search (powerset) method when dealing with 10 or fewer partners, but dynamically switches to a fast, price-sorted Greedy selection algorithm for larger groups to prevent exponential calculation times. Additionally, it maximizes profit margins by employing a time-dependent Boulware concession strategy, demanding highly favorable prices initially and gradually conceding as the negotiation deadline approaches, all while adaptively managing quantity mismatches to avoid shortfall penalties and storage costs.'
METADATA = {
    'id': ID, 'name': NAME, 'class_name': CLASS_NAME,
    'version': VERSION, 'team': TEAM, 'author': AUTHOR,
    'members': MEMBERS, 'country': COUNTRY,
    'institution': INSTITUTION, 'tags': TAGS,
    'uses_llm': USES_LLM, 'description': DESC,
}
# --- END generated metadata ---
