"""SCML 2026 participant team_21095 (agent id 21095, class IsobeAgent).

Generated by scmlweb/python/update_agents_repo.py.
"""
from .isobeagent import IsobeAgent as MAIN_AGENT

__all__ = ["MAIN_AGENT"]

# --- BEGIN generated metadata (scmlweb update_agents_repo.py) ---
ID = 21095
NAME = 'IsobeAgent'
CLASS_NAME = 'IsobeAgent'
VERSION = '3.11.7'
TEAM = 'Team 380'
AUTHOR = 'Hayate Ogata'
MEMBERS = [{'name': '緒方颯', 'institution': 'Nagoya Institute of Technology', 'country': 'Japan'}, {'name': 'Hayate Ogata', 'institution': 'Nagoya Institute of Technology', 'country': 'Japan'}]
COUNTRY = 'Japan'
INSTITUTION = 'Nagoya Institute of Technology'
TAGS = ['Heuristic / Rule-based']
USES_LLM = False
DESC = ''
METADATA = {
    'id': ID, 'name': NAME, 'class_name': CLASS_NAME,
    'version': VERSION, 'team': TEAM, 'author': AUTHOR,
    'members': MEMBERS, 'country': COUNTRY,
    'institution': INSTITUTION, 'tags': TAGS,
    'uses_llm': USES_LLM, 'description': DESC,
}
# --- END generated metadata ---
