import os

__all__ = [
    "SCMLAGENTS_FASTRUN",
    "SCMLAGENTS_RUN2019",
    "SCMLAGENTS_RUN2020",
    "SCMLAGENTS_RUN2021",
    "SCMLAGENTS_RUN2021_TOURNAMENT",
    "SCMLAGENTS_RUN2021_ONESHOT",
    "SCMLAGENTS_RUN2021_ONESHOT_SYNC",
    "SCMLAGENTS_RUN2021_STD",
    "SCMLAGENTS_RUN_GENIUS",
    "SCMLAGENTS_RUN_TOURNAMENTS",
    "SCMLAGENTS_RUN_STD_TOURNAMENTS",
    "SCMLAGENTS_RUN_COLLUSION_TOURNAMENTS",
    "SCMLAGENTS_RUN_SABOTAGE_TOURNAMENTS",
    "SCMLAGENTS_RUN_TEMP_FAILING",
]


def is_enabled(val: str) -> bool:
    return os.environ.get(val, "").lower() in ("true", "yes")


def isnot_disabled(val: str) -> bool:
    return os.environ.get(val, "").lower() not in ("false", "no")


SCMLAGENTS_ON_GITHUB = is_enabled("GITHUB_ACTIONS")
SCMLAGENTS_FASTRUN = isnot_disabled("SCMLAGENTS_FASTRUN") and not SCMLAGENTS_ON_GITHUB
SCMLAGENTS_RUN_TEMP_FAILING = is_enabled("SCMLAGENTS_RUN_TEMP_FAILING")
SCMLAGENTS_RUN2021_ONESHOT = isnot_disabled("SCMLAGENTS_RUN2021_ONESHOT")
SCMLAGENTS_RUN2021_STD = isnot_disabled("SCMLAGENTS_RUN2021_STD")
SCMLAGENTS_RUN2021 = isnot_disabled("SCMLAGENTS_RUN2021")
SCMLAGENTS_RUN2019 = is_enabled("SCMLAGENTS_RUN2019") and not SCMLAGENTS_FASTRUN
SCMLAGENTS_RUN2020 = is_enabled("SCMLAGENTS_RUN2020") and not SCMLAGENTS_FASTRUN
SCMLAGENTS_RUN_GENIUS = is_enabled("SCMLAGENTS_RUN_GENIUS") and not SCMLAGENTS_FASTRUN
SCMLAGENTS_RUN_TOURNAMENTS = (
    is_enabled("SCMLAGENTS_RUN_TOURNAMENTS") and not SCMLAGENTS_FASTRUN
)
SCMLAGENTS_RUN2021_TOURNAMENT = (
    is_enabled("SCMLAGENTS_RUN2021_TOURNAMENT") and not SCMLAGENTS_FASTRUN
)
SCMLAGENTS_RUN2021_ONESHOT_SYNC = (
    is_enabled("SCMLAGENTS_RUN2021_ONESHOT_SYNC") and not SCMLAGENTS_FASTRUN
)
SCMLAGENTS_RUN_STD_TOURNAMENTS = (
    is_enabled("SCMLAGENTS_RUN_STD_TOURNAMENTS") and SCMLAGENTS_RUN_TOURNAMENTS
)
SCMLAGENTS_RUN_COLLUSION_TOURNAMENTS = (
    is_enabled("SCMLAGENTS_RUN_COLLUSION_TOURNAMENTS") and SCMLAGENTS_RUN_TOURNAMENTS
)
SCMLAGENTS_RUN_SABOTAGE_TOURNAMENTS = (
    is_enabled("SCMLAGENTS_RUN_SABOTAGE_TOURNAMENTS") and SCMLAGENTS_RUN_TOURNAMENTS
)
