"""Smoke test for the SCML 2026 (oneshot) participants.

Imports every class registered for this year/track via
`scml_agents.registry.get_participants` and asserts each resolves
to a Python class. Regenerated by
scmlweb/python/update_agents_repo.py.
"""
from negmas.helpers import get_class

from scml_agents.registry import get_participants


def test_all_participants_resolve():
    paths = get_participants(2026, "oneshot")
    if not paths:
        return  # nothing registered yet
    for p in paths:
        cls = get_class(p)
        assert isinstance(cls, type), f"{p} did not resolve to a class"


def test_finalists_subset_of_all():
    all_paths = set(get_participants(2026, "oneshot"))
    finalists = set(get_participants(2026, "oneshot", finalists_only=True))
    winners = set(get_participants(2026, "oneshot", winners_only=True))
    assert finalists <= all_paths
    assert winners <= finalists or winners <= all_paths
