"""SCML 2026 participant team_21803 (agent id 21803, class StdOmegaNegotiator).

Generated by scmlweb/python/update_agents_repo.py.
"""
from .std_agent.entry import StdOmegaNegotiator as MAIN_AGENT

__all__ = ["MAIN_AGENT"]

# --- BEGIN generated metadata (scmlweb update_agents_repo.py) ---
ID = 21803
NAME = 'CodexAgentStd'
CLASS_NAME = 'StdOmegaNegotiator'
VERSION = '2.1.0'
TEAM = 'Team 507'
AUTHOR = 'Ryota GENSEKI'
MEMBERS = [{'name': 'Ryota GENSEKI', 'institution': 'Tokyo University of Agriculture and Technology', 'country': 'Japan'}]
COUNTRY = 'Japan'
INSTITUTION = 'Tokyo University of Agriculture and Technology'
TAGS = ['Reinforcement Learning']
USES_LLM = False
DESC = 'StdOmegaNegotiator is a quantity-first negotiation agent for the SCML 2026 Standard Track. It maintains a daily production target equal to 75% of factory capacity and continuously estimates the input and output quantities required to sustain that target. For same-day negotiations, it uses bounded dynamic programming to select combinations of offers whose total quantity best matches the remaining need, while using price and partner reliability to break ties. This avoids exponential powerset enumeration and keeps response time predictable. Unused partners are assigned to near-future negotiations across the next three days, and future acceptance is capped at 95% of estimated need to limit overcommitment. The agent opens with favorable prices, follows a time-dependent concession curve, and becomes slightly more aggressive late in the simulation. Lightweight success-rate memory prioritizes reliable partners while retaining limited exploration. The final policy was selected through common-random-number screening and same-tournament held-out validation against the top three SCML 2025 Standard agents.'
METADATA = {
    'id': ID, 'name': NAME, 'class_name': CLASS_NAME,
    'version': VERSION, 'team': TEAM, 'author': AUTHOR,
    'members': MEMBERS, 'country': COUNTRY,
    'institution': INSTITUTION, 'tags': TAGS,
    'uses_llm': USES_LLM, 'description': DESC,
}
# --- END generated metadata ---
