"""SCML 2026 participant team_21484 (agent id 21484, class LatticeOneShotAgent).

Generated by scmlweb/python/update_agents_repo.py.
"""
from .latice_oneshot_agent import LatticeOneShotAgent as MAIN_AGENT

__all__ = ["MAIN_AGENT"]

# --- BEGIN generated metadata (scmlweb update_agents_repo.py) ---
ID = 21484
NAME = 'LatticeOneshotAgent'
CLASS_NAME = 'LatticeOneShotAgent'
VERSION = '1.0'
TEAM = 'Team179'
AUTHOR = 'Yuzuru Kitamura'
MEMBERS = [{'name': 'Yuzuru Kitamura', 'institution': 'Tokyo University of Agriculture and Technology', 'country': 'Japan'}]
COUNTRY = 'Japan'
INSTITUTION = 'Tokyo University of Agriculture and Technology'
TAGS = ['Search Algorithms', 'Heuristic / Rule-based', 'Optimization']
USES_LLM = False
DESC = 'This agent uses a synchronized, quantity-focused negotiation strategy for the SCML OneShot track. It evaluates incoming offers jointly across partners and seeks offer combinations that satisfy the agent’s current production needs while limiting both shortfall and disposal risks. Proposal quantities are adapted according to the current negotiation context, observed supply-demand pressure, and partner interaction history.\r\n\r\nThe agent also maintains lightweight online statistics about counter-offer outcomes. These estimates are used to compare the value of accepting current offers with issuing counter-offers, especially in later negotiation stages. Overall, the strategy emphasizes stable need fulfillment, cautious over-ordering, and adaptive partner-aware counter-offer decisions.'
METADATA = {
    'id': ID, 'name': NAME, 'class_name': CLASS_NAME,
    'version': VERSION, 'team': TEAM, 'author': AUTHOR,
    'members': MEMBERS, 'country': COUNTRY,
    'institution': INSTITUTION, 'tags': TAGS,
    'uses_llm': USES_LLM, 'description': DESC,
}
# --- END generated metadata ---
