"""SCML 2026 participant team_20964 (agent id 20964, class BalancedGreedyStdAgent).

Generated by scmlweb/python/update_agents_repo.py.
"""
from .balanced_greedy.balanced_greedy_std_agent import BalancedGreedyStdAgent as MAIN_AGENT

__all__ = ["MAIN_AGENT"]

# --- BEGIN generated metadata (scmlweb update_agents_repo.py) ---
ID = 20964
NAME = 'BalancedGreedyStdAgent'
CLASS_NAME = 'BalancedGreedyStdAgent'
VERSION = '3.11.15'
TEAM = 'Team 341'
AUTHOR = 'Takaya'
MEMBERS = [{'name': 'Takaya', 'institution': 'Nagoya Institute of Technology', 'country': 'Japan'}]
COUNTRY = 'Japan'
INSTITUTION = 'Nagoya Institute of Technology'
TAGS = []
USES_LLM = False
DESC = "BalancedGreedyStdAgent is a conservative Standard-track agent built on two ideas: time-based price concession and needs-based quantity control. When selling, it proposes prices starting near the maximum and concedes toward the midpoint as the negotiation deadline approaches; when buying, it starts near the minimum and concedes upward. Its acceptance thresholds follow the same schedule, so it is demanding early and flexible late. Crucially, it sizes all quantities using the agent-world interface's reported needs (needed_sales and needed_supplies) rather than tracking commitments itself, rejecting offers that exceed the remaining need or once that need is zero. This prevents over-buying and over-selling, limiting inventory and shortfall costs. When selling it requests delivery two steps ahead to allow production time."
METADATA = {
    'id': ID, 'name': NAME, 'class_name': CLASS_NAME,
    'version': VERSION, 'team': TEAM, 'author': AUTHOR,
    'members': MEMBERS, 'country': COUNTRY,
    'institution': INSTITUTION, 'tags': TAGS,
    'uses_llm': USES_LLM, 'description': DESC,
}
# --- END generated metadata ---
