"""SCML 2026 participant team_21165 (agent id 21165, class AgeAgeAgent).

Generated by scmlweb/python/update_agents_repo.py.
"""
from .age_age_agent.age_age_agent import AgeAgeAgent as MAIN_AGENT

__all__ = ["MAIN_AGENT"]

# --- BEGIN generated metadata (scmlweb update_agents_repo.py) ---
ID = 21165
NAME = 'AgeAgeAgent'
CLASS_NAME = 'AgeAgeAgent'
VERSION = '3.11.9'
TEAM = 'Team 404'
AUTHOR = 'MorikawaYuto'
MEMBERS = [{'name': 'MorikawaYuto', 'institution': 'Nagoya Institute of Technology', 'country': 'Japan'}]
COUNTRY = 'Japan'
INSTITUTION = 'Nagoya Institute of Technology'
TAGS = ['Heuristic / Rule-based']
USES_LLM = False
DESC = 'AgeAgeAgent is a negotiation agent designed for the SCML Standard environment. It makes offers by estimating current needs, partner reliability, past trading quantities, average prices, and expected value. For near-term contracts, it emphasizes satisfying production needs and avoiding shortfall, while checking that prices still secure minimum profit. For future contracts, it assigns delivery steps using score-based and knapsack-style selection, prioritizing reliable partners and favorable prices. When incoming offers are evaluated, it groups buy and sell offers by delivery time, builds possible offer subsets, and chooses combinations that balance inventory, existing contracts, exogenous input or output, production capacity, profit, and storage cost. Unprofitable or poorly matched offers are not simply accepted; the agent can rebuild counteroffers using its preferred quantity, delivery time, and valid price, adjusted according to concession behavior and partner success rates. Overall, it aims to trade enough to keep production stable without accepting excessive risk or low-profit deals.'
METADATA = {
    'id': ID, 'name': NAME, 'class_name': CLASS_NAME,
    'version': VERSION, 'team': TEAM, 'author': AUTHOR,
    'members': MEMBERS, 'country': COUNTRY,
    'institution': INSTITUTION, 'tags': TAGS,
    'uses_llm': USES_LLM, 'description': DESC,
}
# --- END generated metadata ---
