"""SCML 2026 participant team_21056 (agent id 21056, class SteadySyncAgent).

Generated by scmlweb/python/update_agents_repo.py.
"""
from .steadysyncagent.agent import SteadySyncAgent as MAIN_AGENT

__all__ = ["MAIN_AGENT"]

# --- BEGIN generated metadata (scmlweb update_agents_repo.py) ---
ID = 21056
NAME = 'SteadySyncAgent'
CLASS_NAME = 'SteadySyncAgent'
VERSION = '0.0.1'
TEAM = 'Team 364'
AUTHOR = 'Sora Kawase'
MEMBERS = [{'name': 'skyriver1126', 'institution': 'Kyoto University', 'country': 'Japan'}, {'name': 'Sora Kawase', 'institution': 'Kyoto University', 'country': 'Japan'}]
COUNTRY = 'Japan'
INSTITUTION = 'Kyoto University'
TAGS = ['Game Theory', 'Economics', 'Heuristic / Rule-based']
USES_LLM = False
DESC = 'SteadySyncAgent is a negotiation agent designed for the SCML OneShot track. It employs a Boulware concession strategy to dynamically adjust its target prices over time, starting with aggressive offers and gradually conceding towards a reservation value. A key innovationis the "Profit-Guardrail" mechanism, which ensures that buying and selling prices are cross-referenced to maintain positive profit margins regardless of market volatility. For managing concurrent negotiations, it uses a "Quantity-First" greedy distribution approach, sorting potential contracts by profitability and prioritizing agreements that fulfill its immediate supply or sales needs. This combination of risk-aware pricing and strategic quantity allocation allows the agent to achieve stable performance across diverse market conditions.'
METADATA = {
    'id': ID, 'name': NAME, 'class_name': CLASS_NAME,
    'version': VERSION, 'team': TEAM, 'author': AUTHOR,
    'members': MEMBERS, 'country': COUNTRY,
    'institution': INSTITUTION, 'tags': TAGS,
    'uses_llm': USES_LLM, 'description': DESC,
}
# --- END generated metadata ---
