"""SCML 2026 participant team_21813 (agent id 21813, class SBDOneShot).

Generated by scmlweb/python/update_agents_repo.py.
"""
from .sbdoneshot_agent import SBDOneShot as MAIN_AGENT

__all__ = ["MAIN_AGENT"]

# --- BEGIN generated metadata (scmlweb update_agents_repo.py) ---
ID = 21813
NAME = 'SBDOneShot'
CLASS_NAME = 'SBDOneShot'
VERSION = '0.6.50'
TEAM = 'Team Ukku'
AUTHOR = 'Hajime Endo'
MEMBERS = [{'name': 'Hajime Endo', 'institution': 'Tokyo University of Agriculture and Technology', 'country': 'Japan'}]
COUNTRY = 'Japan'
INSTITUTION = 'Tokyo University of Agriculture and Technology'
TAGS = ['Deep Learning', 'Reinforcement Learning', 'Psychology']
USES_LLM = False
DESC = 'SBDOneShot is a rule-based agent submitted to the SCML OneShot\r\ntrack. It extends the 2025 OneShot finalist Rchan with a position-\r\naware count-based leverage layer that adjusts the agent’s tolerance for\r\nquantity mismatches according to the supply-chain shape it is placed\r\nin. The leverage classification is decided at initialization time from the\r\nnumber of agents on each production level, so it is fully determinis-\r\ntic and free from the instability of short-window market observations. SBDOneShot does not use a large language model, deep learning, or re-inforcement learning at runtime. Its behavior is produced by transparent heuristics inherited from Rchan and a small additional rule tuned through simulation against the strongest known OneShot agents.'
METADATA = {
    'id': ID, 'name': NAME, 'class_name': CLASS_NAME,
    'version': VERSION, 'team': TEAM, 'author': AUTHOR,
    'members': MEMBERS, 'country': COUNTRY,
    'institution': INSTITUTION, 'tags': TAGS,
    'uses_llm': USES_LLM, 'description': DESC,
}
# --- END generated metadata ---
