"""SCML 2026 participant team_21559 (agent id 21559, class Group4).

Generated by scmlweb/python/update_agents_repo.py.
"""
from .group4 import Group4 as MAIN_AGENT

__all__ = ["MAIN_AGENT"]

# --- BEGIN generated metadata (scmlweb update_agents_repo.py) ---
ID = 21559
NAME = 'MyAgent17803196313323'
CLASS_NAME = 'Group4'
VERSION = '0.66.81'
TEAM = 'Team 484'
AUTHOR = 'Hamid Majidi Balanji'
MEMBERS = [{'name': 'Hamid Majidi Balanji', 'institution': 'Özyeğin University', 'country': 'Türkiye'}]
COUNTRY = 'Türkiye'
INSTITUTION = 'Özyeğin University'
TAGS = []
USES_LLM = False
DESC = 'This agent for the ANAC 2026 SCML Standard track manages production and negotiation using a four-part architecture. It employs a Boulware bidding strategy that prevents value leakage by anchoring minimum prices to the prevailing market. Bidding and acceptance are decoupled; a steeper acceptance curve secures agreements near deadlines , while an over-commit guard prevents capacity breaches. Production is strictly demand-driven, eliminating speculative manufacturing to avoid disposal penalties. Finally, an opponent classifier categorizes partners into behavioral archetypes based on trust, price, and reliability , dynamically adjusting the utility acceptance threshold.'
METADATA = {
    'id': ID, 'name': NAME, 'class_name': CLASS_NAME,
    'version': VERSION, 'team': TEAM, 'author': AUTHOR,
    'members': MEMBERS, 'country': COUNTRY,
    'institution': INSTITUTION, 'tags': TAGS,
    'uses_llm': USES_LLM, 'description': DESC,
}
# --- END generated metadata ---
