"""SCML 2026 participant team_22272 (agent id 22272, class SupmerkosV3).

Generated by scmlweb/python/update_agents_repo.py.
"""
from .supmerkos_v3 import SupmerkosV3 as MAIN_AGENT

__all__ = ["MAIN_AGENT"]

# --- BEGIN generated metadata (scmlweb update_agents_repo.py) ---
ID = 22272
NAME = 'SupmerkosV3'
CLASS_NAME = 'SupmerkosV3'
VERSION = '0.3.1'
TEAM = 'Team 412'
AUTHOR = 'Kosuke Nakata'
MEMBERS = [{'name': 'Kosuke Nakata', 'institution': 'Tokyo University of Agriculture and Technology', 'country': 'Japan'}]
COUNTRY = 'Japan'
INSTITUTION = 'Tokyo University of Agriculture and Technology'
TAGS = ['Search Algorithms', 'Heuristic / Rule-based', 'Optimization']
USES_LLM = False
DESC = 'SupmerkosV3 is a deterministic rule-based Standard-track agent built around\r\ncurrent-step execution quality. It evaluates simultaneous offers as bundles\r\ninstead of independent deals, using the official utility function when possible\r\nand selecting the subset that best matches immediate supply and sales needs.\r\nIts proposal policy searches over a small set of quantities and price\r\nconcession levels, balancing production-line utilization, inventory pressure,\r\nand the risk of overcommitting. Future contracts are treated conservatively and\r\naccepted only when they are close in time, profitable, and compatible with\r\nexpected production capacity. The agent keeps lightweight partner statistics to\r\nslightly reward reliable counterparts, while remaining fully heuristic and not\r\nusing learning, LLMs, copied opponent code, or external online information.'
METADATA = {
    'id': ID, 'name': NAME, 'class_name': CLASS_NAME,
    'version': VERSION, 'team': TEAM, 'author': AUTHOR,
    'members': MEMBERS, 'country': COUNTRY,
    'institution': INSTITUTION, 'tags': TAGS,
    'uses_llm': USES_LLM, 'description': DESC,
}
# --- END generated metadata ---
