"""SCML 2026 participant team_21084 (agent id 21084, class EmSel).

Generated by scmlweb/python/update_agents_repo.py.
"""
from .emsel import EmSel as MAIN_AGENT

__all__ = ["MAIN_AGENT"]

# --- BEGIN generated metadata (scmlweb update_agents_repo.py) ---
ID = 21084
NAME = 'EmSel'
CLASS_NAME = 'EmSel'
VERSION = '3.10.0'
TEAM = 'Team EmSel'
AUTHOR = 'Emre Karaarslan'
MEMBERS = [{'name': 'Emre Karaarslan', 'institution': 'Özyeğin University', 'country': 'Türkiye'}, {'name': 'Selen Recepoğlu', 'institution': 'Özyeğin University', 'country': 'Türkiye'}]
COUNTRY = 'Türkiye'
INSTITUTION = 'Özyeğin University'
TAGS = ['Economics', 'Search Algorithms', 'Heuristic / Rule-based']
USES_LLM = False
DESC = 'An automated negotiation agent developed for the SCML 2026 tournament using time-based compromise strategies.'
METADATA = {
    'id': ID, 'name': NAME, 'class_name': CLASS_NAME,
    'version': VERSION, 'team': TEAM, 'author': AUTHOR,
    'members': MEMBERS, 'country': COUNTRY,
    'institution': INSTITUTION, 'tags': TAGS,
    'uses_llm': USES_LLM, 'description': DESC,
}
# --- END generated metadata ---
