"""SCML 2026 participant team_21303 (agent id 21303, class COW).

Generated by scmlweb/python/update_agents_repo.py.
"""
from .cow import COW as MAIN_AGENT

__all__ = ["MAIN_AGENT"]

# --- BEGIN generated metadata (scmlweb update_agents_repo.py) ---
ID = 21303
NAME = 'COW'
CLASS_NAME = 'COW'
VERSION = '0.12.6'
TEAM = 'Team 389'
AUTHOR = 'Naoki Ushida'
MEMBERS = [{'name': 'Naoki Ushida', 'institution': 'Nagoya Institute of Technology', 'country': 'Japan'}]
COUNTRY = 'Japan'
INSTITUTION = 'Nagoya Institute of Technology'
TAGS = ['Game Theory', 'Heuristic / Rule-based']
USES_LLM = False
DESC = ''
METADATA = {
    'id': ID, 'name': NAME, 'class_name': CLASS_NAME,
    'version': VERSION, 'team': TEAM, 'author': AUTHOR,
    'members': MEMBERS, 'country': COUNTRY,
    'institution': INSTITUTION, 'tags': TAGS,
    'uses_llm': USES_LLM, 'description': DESC,
}
# --- END generated metadata ---
