"""SCML 2026 participant team_21195 (agent id 21195, class Agent01StdAgent).

Generated by scmlweb/python/update_agents_repo.py.
"""
from .agent01std.core.agent import Agent01StdAgent as MAIN_AGENT

__all__ = ["MAIN_AGENT"]

# --- BEGIN generated metadata (scmlweb update_agents_repo.py) ---
ID = 21195
NAME = 'agent01std'
CLASS_NAME = 'Agent01StdAgent'
VERSION = '3.11.8'
TEAM = 'Team 403'
AUTHOR = 'Yifan Zhang'
MEMBERS = [{'name': 'Yifan Zhang', 'institution': 'South China University of Technology', 'country': 'China'}]
COUNTRY = 'China'
INSTITUTION = 'South China University of Technology'
TAGS = []
USES_LLM = False
DESC = ''
METADATA = {
    'id': ID, 'name': NAME, 'class_name': CLASS_NAME,
    'version': VERSION, 'team': TEAM, 'author': AUTHOR,
    'members': MEMBERS, 'country': COUNTRY,
    'institution': INSTITUTION, 'tags': TAGS,
    'uses_llm': USES_LLM, 'description': DESC,
}
# --- END generated metadata ---
