"""SCML 2026 participant team_21747 (agent id 21747, class KotaAgent).

Generated by scmlweb/python/update_agents_repo.py.
"""
from .kotaagent.kotaagent import KotaAgent as MAIN_AGENT

__all__ = ["MAIN_AGENT"]

# --- BEGIN generated metadata (scmlweb update_agents_repo.py) ---
ID = 21747
NAME = 'KotaAgent'
CLASS_NAME = 'KotaAgent'
VERSION = '0.0.1'
TEAM = 'Team 337'
AUTHOR = 'Hibino-Kota'
MEMBERS = [{'name': 'Hibino-Kota', 'institution': 'Nagoya Institute of Technology', 'country': 'Japan'}]
COUNTRY = 'Japan'
INSTITUTION = 'Nagoya Institute of Technology'
TAGS = []
USES_LLM = False
DESC = ''
METADATA = {
    'id': ID, 'name': NAME, 'class_name': CLASS_NAME,
    'version': VERSION, 'team': TEAM, 'author': AUTHOR,
    'members': MEMBERS, 'country': COUNTRY,
    'institution': INSTITUTION, 'tags': TAGS,
    'uses_llm': USES_LLM, 'description': DESC,
}
# --- END generated metadata ---
