"""SCML 2026 participant team_21653 (agent id 21653, class HorizonAwareAgent).

Generated by scmlweb/python/update_agents_repo.py.
"""
from .horizon_aware_agent import HorizonAwareAgent as MAIN_AGENT

__all__ = ["MAIN_AGENT"]

# --- BEGIN generated metadata (scmlweb update_agents_repo.py) ---
ID = 21653
NAME = 'HorizonAwareAgent'
CLASS_NAME = 'HorizonAwareAgent'
VERSION = '0.80.77'
TEAM = 'Team179'
AUTHOR = 'Yuzuru Kitamura'
MEMBERS = [{'name': 'Yuzuru Kitamura', 'institution': 'Tokyo University of Agriculture and Technology', 'country': 'Japan'}]
COUNTRY = 'Japan'
INSTITUTION = 'Tokyo University of Agriculture and Technology'
TAGS = []
USES_LLM = False
DESC = 'HorizonAwareAgent is a horizon-aware negotiation agent designed to manage future production and sales commitments proactively rather than focusing only on the current step.\r\n\r\nThe agent uses different negotiation policies depending on its supply-chain level. At the first and middle levels, it emphasizes securing future sales while avoiding excessive exposure to partners that are unlikely to accept profitable offers. It learns simple partner-specific response patterns from accepted offers and then adjusts future proposals based on whether each partner tends to accept high-price/high-quantity offers, low-price counter offers, or only immediately profitable incoming offers.'
METADATA = {
    'id': ID, 'name': NAME, 'class_name': CLASS_NAME,
    'version': VERSION, 'team': TEAM, 'author': AUTHOR,
    'members': MEMBERS, 'country': COUNTRY,
    'institution': INSTITUTION, 'tags': TAGS,
    'uses_llm': USES_LLM, 'description': DESC,
}
# --- END generated metadata ---
