"""SCML 2026 participant team_21707 (agent id 21707, class SKRI).

Generated by scmlweb/python/update_agents_repo.py.
"""
from .skri import SKRI as MAIN_AGENT

__all__ = ["MAIN_AGENT"]

# --- BEGIN generated metadata (scmlweb update_agents_repo.py) ---
ID = 21707
NAME = 'SKRI'
CLASS_NAME = 'SKRI'
VERSION = '0.18.56'
TEAM = 'Team 389'
AUTHOR = 'Naoki Ushida'
MEMBERS = [{'name': 'Naoki Ushida', 'institution': 'Nagoya Institute of Technology', 'country': 'Japan'}]
COUNTRY = 'Japan'
INSTITUTION = 'Nagoya Institute of Technology'
TAGS = []
USES_LLM = False
DESC = ''
METADATA = {
    'id': ID, 'name': NAME, 'class_name': CLASS_NAME,
    'version': VERSION, 'team': TEAM, 'author': AUTHOR,
    'members': MEMBERS, 'country': COUNTRY,
    'institution': INSTITUTION, 'tags': TAGS,
    'uses_llm': USES_LLM, 'description': DESC,
}
# --- END generated metadata ---
