# SCML 2026 (oneshot) participants.
# Regenerated by scmlweb/python/update_agents_repo.py.
import importlib as _importlib

__all__ = []
__import_errors__ = {}

_TEAMS = ["team_21022", "team_21041", "team_21056", "team_21089", "team_21095", "team_21155", "team_21196", "team_21244", "team_21484", "team_21562", "team_21619", "team_21637", "team_21798", "team_21799", "team_21804", "team_21813"]

for _t in _TEAMS:
    try:
        globals()[_t] = _importlib.import_module(f'{__name__}.{_t}')
        __all__.append(_t)
    except Exception as _e:  # pragma: no cover - per-submission
        __import_errors__[_t] = repr(_e)
