"""SCML 2026 participant team_20941 (agent id 20941, class OkAgent).

Generated by scmlweb/python/update_agents_repo.py.
"""
from .okagent import OkAgent as MAIN_AGENT

__all__ = ["MAIN_AGENT"]

# --- BEGIN generated metadata (scmlweb update_agents_repo.py) ---
ID = 20941
NAME = 'okagent'
CLASS_NAME = 'OkAgent'
VERSION = '0.0.1'
TEAM = 'Team 336'
AUTHOR = 'Kohga Okashita'
MEMBERS = [{'name': 'Kohga Okashita', 'institution': 'Nagoya Institute of Technology', 'country': 'Japan'}]
COUNTRY = 'Japan'
INSTITUTION = 'Nagoya Institute of Technology'
TAGS = ['Heuristic / Rule-based']
USES_LLM = False
DESC = 'This agent follows a price-driven inventory strategy. It aggressively purchases raw materials when offered prices are significantly below the estimated market price and may buy additional quantities when prices are favorable. To avoid excessive inventory costs, it maintains an inventory limit based on production capacity. On the selling side, it accepts offers only when prices are sufficiently profitable and rejects low-priced offers by proposing counteroffers. The agent aims to maximize profit by exploiting temporary price advantages while controlling inventory risk and avoiding unfavorable transactions.'
METADATA = {
    'id': ID, 'name': NAME, 'class_name': CLASS_NAME,
    'version': VERSION, 'team': TEAM, 'author': AUTHOR,
    'members': MEMBERS, 'country': COUNTRY,
    'institution': INSTITUTION, 'tags': TAGS,
    'uses_llm': USES_LLM, 'description': DESC,
}
# --- END generated metadata ---
