"""SCML 2026 participant team_21022 (agent id 21022, class EFRDistOneShotAgent).

Generated by scmlweb/python/update_agents_repo.py.
"""
from .efr_dist.agent import EFRDistOneShotAgent as MAIN_AGENT

__all__ = ["MAIN_AGENT"]

# --- BEGIN generated metadata (scmlweb update_agents_repo.py) ---
ID = 21022
NAME = 'EFRDist'
CLASS_NAME = 'EFRDistOneShotAgent'
VERSION = '0.0.1'
TEAM = 'Team 353'
AUTHOR = 'Mason Hagan'
MEMBERS = [{'name': 'Mason Hagan', 'institution': 'Brown University', 'country': 'United States'}]
COUNTRY = 'United States'
INSTITUTION = 'Brown University'
TAGS = ['Game Theory', 'Heuristic / Rule-based']
USES_LLM = False
DESC = "EFRDistOneShotAgent decomposes the OneShot day by responsibility. Allocation of the day's needed quantity across partners, and the choice of which combination of standing offers to accept, are delegated to a need-distribution heuristic (the SyncRandom backbone), since that joint-across-partners state lies outside any bilateral information set. Unit pricing, together with a price gate on acceptance, is governed by a coarse-correlated-equilibrium policy solved offline with extensive-form regret minimization on a small two-player abstraction of one bilateral negotiation. At runtime the agent is pure dictionary lookup over the precomputed policy, with a guarded fallback to the heuristic on any uncovered state. The pricing policy is genuinely in the loop, but by design the distribution heuristic carries most of the score."
METADATA = {
    'id': ID, 'name': NAME, 'class_name': CLASS_NAME,
    'version': VERSION, 'team': TEAM, 'author': AUTHOR,
    'members': MEMBERS, 'country': COUNTRY,
    'institution': INSTITUTION, 'tags': TAGS,
    'uses_llm': USES_LLM, 'description': DESC,
}
# --- END generated metadata ---
