"""SCML 2026 participant team_21021 (agent id 21021, class ArionAgent).

Generated by scmlweb/python/update_agents_repo.py.
"""
from .arion_strategists.arion_agent import ArionAgent as MAIN_AGENT

__all__ = ["MAIN_AGENT"]

# --- BEGIN generated metadata (scmlweb update_agents_repo.py) ---
ID = 21021
NAME = 'ArionAgent'
CLASS_NAME = 'ArionAgent'
VERSION = '2.0.0'
TEAM = 'Arion Strategists'
AUTHOR = 'Muhammad Raees Azam'
MEMBERS = [{'name': 'Muhammad Raees Azam', 'institution': 'Özyeğin University', 'country': 'Türkiye'}, {'name': 'Mehak Arshid', 'institution': 'Özyeğin University', 'country': 'Türkiye'}]
COUNTRY = 'Türkiye'
INSTITUTION = 'Özyeğin University'
TAGS = ['Game Theory', 'Economics', 'Search Algorithms', 'Heuristic / Rule-based', 'Optimization']
USES_LLM = False
DESC = 'ArionAgent is a negotiation agent for the SCML standard track built on top of SyncRandomStdAgent. Its core idea is to combine practical rule-based decision making with utility-aware offer selection and adaptive pricing. At each step, it estimates current buy/sell needs, evaluates candidate bundles of offers, and accepts sets that satisfy quantity goals while passing a utility floor. For bundle construction, it supports baseline subset selection and search-style exploration (including beam-style ranking in non-default variants). For counter-offers, the default strategy (“game”) uses reservation-price logic inspired by Nash bargaining, then adjusts with lightweight partner memory (best observed buy/sell prices). The pipeline is phase-based (bundle acceptance, salvage, price checks, and counters), designed for robust performance under different market conditions.'
METADATA = {
    'id': ID, 'name': NAME, 'class_name': CLASS_NAME,
    'version': VERSION, 'team': TEAM, 'author': AUTHOR,
    'members': MEMBERS, 'country': COUNTRY,
    'institution': INSTITUTION, 'tags': TAGS,
    'uses_llm': USES_LLM, 'description': DESC,
}
# --- END generated metadata ---
