# SCML 2026 (standard) participants.
# Regenerated by scmlweb/python/update_agents_repo.py.
import importlib as _importlib

__all__ = []
__import_errors__ = {}

_TEAMS = ["team_20941", "team_20964", "team_21021", "team_21084", "team_21127", "team_21165", "team_21195", "team_21201", "team_21282", "team_21303", "team_21313", "team_21559", "team_21650", "team_21653", "team_21683", "team_21695", "team_21747", "team_21800", "team_21803", "team_22272"]

for _t in _TEAMS:
    try:
        globals()[_t] = _importlib.import_module(f'{__name__}.{_t}')
        __all__.append(_t)
    except Exception as _e:  # pragma: no cover - per-submission
        __import_errors__[_t] = repr(_e)
