"""SCML 2026 participant team_21313 (agent id 21313, class SugaiAgent).

Generated by scmlweb/python/update_agents_repo.py.
"""
from .sugai_agent.sugai_agent import SugaiAgent as MAIN_AGENT

__all__ = ["MAIN_AGENT"]

# --- BEGIN generated metadata (scmlweb update_agents_repo.py) ---
ID = 21313
NAME = 'SugaiAgent'
CLASS_NAME = 'SugaiAgent'
VERSION = '3.14.2'
TEAM = 'Team 328'
AUTHOR = 'Toshiki Sugai'
MEMBERS = [{'name': 'Toshiki Sugai', 'institution': 'NIT', 'country': 'Japan'}]
COUNTRY = 'Japan'
INSTITUTION = 'NIT'
TAGS = []
USES_LLM = False
DESC = ''
METADATA = {
    'id': ID, 'name': NAME, 'class_name': CLASS_NAME,
    'version': VERSION, 'team': TEAM, 'author': AUTHOR,
    'members': MEMBERS, 'country': COUNTRY,
    'institution': INSTITUTION, 'tags': TAGS,
    'uses_llm': USES_LLM, 'description': DESC,
}
# --- END generated metadata ---
