"""SCML 2026 participant team_21619 (agent id 21619, class Supvelikos).

Generated by scmlweb/python/update_agents_repo.py.
"""
from .supvelikos import Supvelikos as MAIN_AGENT

__all__ = ["MAIN_AGENT"]

# --- BEGIN generated metadata (scmlweb update_agents_repo.py) ---
ID = 21619
NAME = 'supvelikos'
CLASS_NAME = 'Supvelikos'
VERSION = '0.18.7'
TEAM = 'Team 412'
AUTHOR = 'Kosuke Nakata'
MEMBERS = [{'name': 'Kosuke Nakata', 'institution': 'Tokyo University of Agriculture and Technology', 'country': 'Japan'}]
COUNTRY = 'Japan'
INSTITUTION = 'Tokyo University of Agriculture and Technology'
TAGS = ['Search Algorithms', 'Heuristic / Rule-based', 'Optimization']
USES_LLM = False
DESC = 'Supvelikos is a synchronous negotiation agent designed for the SCML OneShot Track. It evaluates offers as portfolios rather than accepting each offer independently. In every negotiation round, the agent enumerates feasible subsets of received offers and selects a combination by considering the difference from its required quantity, quantity-weighted contract value, and utility. After accepting the selected offers, it reallocates the remaining quantity among unresolved partners. Supvelikos initially overorders to reduce the risk of failed negotiations, then gradually decreases the excess quantity as the deadline approaches. It also divides the feasible price range into several intervals and assigns different intervals to different partners, enabling broad price exploration within a single round. Partner success and failure histories are used as weak reliability signals, allowing adaptation without excessive dependence on previously observed opponents. This combination of portfolio selection, adaptive quantity allocation, and stratified price exploration aims to balance agreement probability, quantity consistency, and profitability.'
METADATA = {
    'id': ID, 'name': NAME, 'class_name': CLASS_NAME,
    'version': VERSION, 'team': TEAM, 'author': AUTHOR,
    'members': MEMBERS, 'country': COUNTRY,
    'institution': INSTITUTION, 'tags': TAGS,
    'uses_llm': USES_LLM, 'description': DESC,
}
# --- END generated metadata ---
