"""SCML 2026 participant team_21799 (agent id 21799, class Ysi).

Generated by scmlweb/python/update_agents_repo.py.
"""
from .ysi import Ysi as MAIN_AGENT

__all__ = ["MAIN_AGENT"]

# --- BEGIN generated metadata (scmlweb update_agents_repo.py) ---
ID = 21799
NAME = 'Ysi'
CLASS_NAME = 'Ysi'
VERSION = '0.1.2'
TEAM = 'Team 497'
AUTHOR = 'Ryoshin Hatakeyama'
MEMBERS = [{'name': 'Ryoshin Hatakeyama', 'institution': 'Tokyo University of Agriculture and Technology', 'country': 'Japan'}]
COUNTRY = 'Japan'
INSTITUTION = 'Tokyo University of Agriculture and Technology'
TAGS = ['Economics', 'Search Algorithms', 'Heuristic / Rule-based', 'Optimization']
USES_LLM = False
DESC = "Ysi is a synchronous OneShot agent whose central goal is to match the quantity it buys and sells each day, since unsold input incurs disposal cost and unmet output incurs a shortfall penalty. Rather than answering each bilateral negotiation in isolation, Ysi treats all concurrent offers on one side of the market as a portfolio. When selling (L0), it estimates each buyer's acceptance probability with a smoothed Beta(1,1) estimator and allocates requested quantities by greedily minimizing the expected under-/over-selling penalty — a newsvendor formulation — with an allocation cap to control tail risk. When buying (L1), it follows a patient, cost-averse policy: it anchors at low prices and concedes only as far as the shortfall-to-disposal cost ratio requires. Selling aggressiveness is further modulated by a market-favorability signal computed from trading prices, production cost, and disposal cost, so the agent holds out for higher prices in favorable markets and concedes earlier when excess risk is high. Acceptance is always decided over combinations of offers to keep the daily input/output quantity balanced."
METADATA = {
    'id': ID, 'name': NAME, 'class_name': CLASS_NAME,
    'version': VERSION, 'team': TEAM, 'author': AUTHOR,
    'members': MEMBERS, 'country': COUNTRY,
    'institution': INSTITUTION, 'tags': TAGS,
    'uses_llm': USES_LLM, 'description': DESC,
}
# --- END generated metadata ---
