"""SCML 2026 participant team_21155 (agent id 21155, class TimeWeightedAgent).

Generated by scmlweb/python/update_agents_repo.py.
"""
from .time_weighted_agent2 import TimeWeightedAgent as MAIN_AGENT

__all__ = ["MAIN_AGENT"]

# --- BEGIN generated metadata (scmlweb update_agents_repo.py) ---
ID = 21155
NAME = 'TimeWeightedAgent'
CLASS_NAME = 'TimeWeightedAgent'
VERSION = '3.12.18'
TEAM = 'Team 400'
AUTHOR = 'ishigami'
MEMBERS = [{'name': 'ishigami', 'institution': 'Nagoya Institute of Technology', 'country': 'Japan'}]
COUNTRY = 'Japan'
INSTITUTION = 'Nagoya Institute of Technology'
TAGS = ['Search Algorithms']
USES_LLM = False
DESC = 'Engineered to exploit the penalty mechanics of SCML-OneShot, the TimeWeightedAgent features a dual-layered architecture that ruthlessly separates risk mitigation from profit maximization. During the acceptance phase, it prioritizes absolute penalty avoidance over dynamic weighting by enforcing a static, quantity-first utility function (Static Alpha). By evaluating the powerset of all active offers against a time-decaying, urgency-aware threshold, the agent mathematically locks in the optimal contract combination.\r\nSimultaneously, the agent acts as a real-time market sensor. By tracking the global supply-to-need ratio, it powers a highly responsive Supply & Demand Linked Pricing strategy. It executes a calculated "Deadline Trap," refusing early compromises and holding aggressive prices until the final 5% of the negotiation, using micro-random noise (Jitter) to shatter opponent deadlocks. Finally, counter-offers are deployed via a strict Waterfall Allocation mechanism that rewards partners based on their time-weighted transaction history, forging robust and dependable supply pipelines.'
METADATA = {
    'id': ID, 'name': NAME, 'class_name': CLASS_NAME,
    'version': VERSION, 'team': TEAM, 'author': AUTHOR,
    'members': MEMBERS, 'country': COUNTRY,
    'institution': INSTITUTION, 'tags': TAGS,
    'uses_llm': USES_LLM, 'description': DESC,
}
# --- END generated metadata ---
