"""SCML 2026 participant team_21562 (agent id 21562, class Group3).

Generated by scmlweb/python/update_agents_repo.py.
"""
from .group3 import Group3 as MAIN_AGENT

__all__ = ["MAIN_AGENT"]

# --- BEGIN generated metadata (scmlweb update_agents_repo.py) ---
ID = 21562
NAME = 'Group3'
CLASS_NAME = 'Group3'
VERSION = '1.0'
TEAM = 'Team 491'
AUTHOR = 'Yeabsira Simeka Maru'
MEMBERS = [{'name': 'Yeabsira Simeka Maru', 'institution': 'Özyeğin University', 'country': 'Türkiye'}]
COUNTRY = 'Türkiye'
INSTITUTION = 'Özyeğin University'
TAGS = ['Bayesian Methods', 'Game Theory', 'Economics', 'Heuristic / Rule-based', 'Optimization', 'Simulation / Monte Carlo']
USES_LLM = False
DESC = ''
METADATA = {
    'id': ID, 'name': NAME, 'class_name': CLASS_NAME,
    'version': VERSION, 'team': TEAM, 'author': AUTHOR,
    'members': MEMBERS, 'country': COUNTRY,
    'institution': INSTITUTION, 'tags': TAGS,
    'uses_llm': USES_LLM, 'description': DESC,
}
# --- END generated metadata ---
