"""SCML 2026 participant team_21041 (agent id 21041, class PenaltyAvoidAgent).

Generated by scmlweb/python/update_agents_repo.py.
"""
from .penalty_avoid.penalty_avoid_agent import PenaltyAvoidAgent as MAIN_AGENT

__all__ = ["MAIN_AGENT"]

# --- BEGIN generated metadata (scmlweb update_agents_repo.py) ---
ID = 21041
NAME = 'PenaltyAvoid'
CLASS_NAME = 'PenaltyAvoidAgent'
VERSION = '1'
TEAM = 'Team 357'
AUTHOR = 'Tarek Medhat'
MEMBERS = [{'name': 'Tarek Medhat', 'institution': 'Assiut University', 'country': 'Egypt'}]
COUNTRY = 'Egypt'
INSTITUTION = 'Assiut University'
TAGS = []
USES_LLM = False
DESC = ''
METADATA = {
    'id': ID, 'name': NAME, 'class_name': CLASS_NAME,
    'version': VERSION, 'team': TEAM, 'author': AUTHOR,
    'members': MEMBERS, 'country': COUNTRY,
    'institution': INSTITUTION, 'tags': TAGS,
    'uses_llm': USES_LLM, 'description': DESC,
}
# --- END generated metadata ---
