"""SCML 2026 participant team_21683 (agent id 21683, class SuperimagentZ).

Generated by scmlweb/python/update_agents_repo.py.
"""
from .agent_v2 import SuperimagentZ as MAIN_AGENT

__all__ = ["MAIN_AGENT"]

# --- BEGIN generated metadata (scmlweb update_agents_repo.py) ---
ID = 21683
NAME = 'SuperimagentZ'
CLASS_NAME = 'SuperimagentZ'
VERSION = '4'
TEAM = 'Team 342'
AUTHOR = 'Aoi Imazeki'
MEMBERS = [{'name': 'Aoi Imazeki', 'institution': 'Nagoya Institute of Technology', 'country': 'Japan'}]
COUNTRY = 'Japan'
INSTITUTION = 'Nagoya Institute of Technology'
TAGS = []
USES_LLM = False
DESC = "SuperimagentZ is a robust heuristic agent for the SCML Standard track. Built on StdSyncAgent, it applies one uniform policy to every production level, sizing each day's buying and selling from a per-step account of already-contracted supplies and sales so it neither overbuys (disposal cost) nor oversells (shortfall penalties). Its main contribution over prior finalist agents is exogenous-aware edge handling: at the first level it stops buying raw material that arrives exogenously, and at the last level it buys enough to meet its exogenous sales obligation, removing avoidable shortfalls. Each round it accepts the subset of current offers closest to its remaining need, breaking ties by price and partner reliability, while future contracts keep a near-future bias. Prices follow a time-based concession curve toward a safe floor, and hard commitment and price caps bound the worst case. Every design choice was validated by paired comparison"
METADATA = {
    'id': ID, 'name': NAME, 'class_name': CLASS_NAME,
    'version': VERSION, 'team': TEAM, 'author': AUTHOR,
    'members': MEMBERS, 'country': COUNTRY,
    'institution': INSTITUTION, 'tags': TAGS,
    'uses_llm': USES_LLM, 'description': DESC,
}
# --- END generated metadata ---
