"""SCML 2026 participant team_21282 (agent id 21282, class TakaLinkAgent).

Generated by scmlweb/python/update_agents_repo.py.
"""
from .taka_link_agent import TakaLinkAgent as MAIN_AGENT

__all__ = ["MAIN_AGENT"]

# --- BEGIN generated metadata (scmlweb update_agents_repo.py) ---
ID = 21282
NAME = 'TakaLinkAgent'
CLASS_NAME = 'TakaLinkAgent'
VERSION = '3.11.18'
TEAM = 'TakaTakaWorks'
AUTHOR = 'Takafumi Omori'
MEMBERS = [{'name': 'Takafumi Omori', 'institution': 'Nagoya Institute of Technology', 'country': 'Japan'}]
COUNTRY = 'Japan'
INSTITUTION = 'Nagoya Institute of Technology'
TAGS = []
USES_LLM = False
DESC = 'TakaLinkAgent is a synchronous negotiation agent designed for the standard SCML environment. Its strategy integrates adaptive pricing, selective partner engagement, and inventory-aware planning. The agent maintains a target stock buffer, performs cautious procurement to reduce supply shortages, and selectively triggers emergency buying only in early critical states. For selling, it applies reservation-aware capacity control to prevent overcommitment and adjusts prices downward under inventory pressure to improve throughput. Partner choice and offer allocation are guided by estimated reliability and historical negotiation outcomes. The overall objective is robust profitability: minimizing catastrophic failures, controlling inventory risk, and achieving stable performance across heterogeneous market conditions.'
METADATA = {
    'id': ID, 'name': NAME, 'class_name': CLASS_NAME,
    'version': VERSION, 'team': TEAM, 'author': AUTHOR,
    'members': MEMBERS, 'country': COUNTRY,
    'institution': INSTITUTION, 'tags': TAGS,
    'uses_llm': USES_LLM, 'description': DESC,
}
# --- END generated metadata ---
