"""SCML 2026 participant team_21650 (agent id 21650, class SBD).

Generated by scmlweb/python/update_agents_repo.py.
"""
from .sbd_agent import SBD as MAIN_AGENT

__all__ = ["MAIN_AGENT"]

# --- BEGIN generated metadata (scmlweb update_agents_repo.py) ---
ID = 21650
NAME = 'SBD'
CLASS_NAME = 'SBD'
VERSION = '0.20.45'
TEAM = 'Team Ukku'
AUTHOR = 'Hajime Endo'
MEMBERS = [{'name': 'Hajime Endo', 'institution': 'Tokyo University of Agriculture and Technology', 'country': 'Japan'}]
COUNTRY = 'Japan'
INSTITUTION = 'Tokyo University of Agriculture and Technology'
TAGS = ['Deep Learning', 'Reinforcement Learning']
USES_LLM = False
DESC = 'SBD is a rule-based SCML Standard agent that adapts its quantity planning to its supply-chain position. At the first level, it prioritizes selling available daily supply and selects synchronized offer subsets using a utility-aware rule. At the middle level, it estimates downstream demand from public exogenous summaries and adjusts its operating cap to balance sales opportunities with conservative procurement. At the last level, it uses realized exogenous demand plus a small safety margin on low-demand days and a capacity-based target on high-demand days. Across all positions, SBD tracks partner reliability, distributes quantities toward promising partners, uses adaptive prices, and keeps future offers short-horizon. 0.0, 5/5 25% DP no.  final0622'
METADATA = {
    'id': ID, 'name': NAME, 'class_name': CLASS_NAME,
    'version': VERSION, 'team': TEAM, 'author': AUTHOR,
    'members': MEMBERS, 'country': COUNTRY,
    'institution': INSTITUTION, 'tags': TAGS,
    'uses_llm': USES_LLM, 'description': DESC,
}
# --- END generated metadata ---
