"""SCML 2026 participant team_21695 (agent id 21695, class Rohn).

Generated by scmlweb/python/update_agents_repo.py.
"""
from .rohn import Rohn as MAIN_AGENT

__all__ = ["MAIN_AGENT"]

# --- BEGIN generated metadata (scmlweb update_agents_repo.py) ---
ID = 21695
NAME = 'Rohn'
CLASS_NAME = 'Rohn'
VERSION = '0.1.2'
TEAM = 'Team 497'
AUTHOR = 'Ryoshin Hatakeyama'
MEMBERS = [{'name': 'Ryoshin Hatakeyama', 'institution': 'Tokyo University of Agriculture and Technology', 'country': 'Japan'}]
COUNTRY = 'Japan'
INSTITUTION = 'Tokyo University of Agriculture and Technology'
TAGS = ['Economics', 'Search Algorithms', 'Heuristic / Rule-based', 'Optimization']
USES_LLM = False
DESC = 'Rohn is a layer-adaptive negotiation agent for the SCML Standard Track.\r\nAt initialization, it fixes its supply-chain position as L0, middle, or last layer, and dispatches every negotiation method to layer-specific logic.\r\nIts negotiation skeleton is based on AS0, while the last-layer buying ceiling and price concession strategy are adapted from CautiousStdAgent.\r\nOn top of these components, Rohn introduces storage-cost-aware price control: a Profit Band that accepts only profitable contracts, an L0 inventory-clearance engine that sells incoming stock before storage costs accumulate, and a market-price estimation cap.\r\nIt also incorporates risk-aware quantity control through an inventory guard, as well as demand-following procurement using a break-even buffer and a demand floor.\r\nIn simulations across 998 worlds, Rohn matches strong baselines while achieving the highest stability.'
METADATA = {
    'id': ID, 'name': NAME, 'class_name': CLASS_NAME,
    'version': VERSION, 'team': TEAM, 'author': AUTHOR,
    'members': MEMBERS, 'country': COUNTRY,
    'institution': INSTITUTION, 'tags': TAGS,
    'uses_llm': USES_LLM, 'description': DESC,
}
# --- END generated metadata ---
