"""SCML 2026 participant team_21196 (agent id 21196, class YamashitaAgent).

Generated by scmlweb/python/update_agents_repo.py.
"""
from .yamashitaagent import YamashitaAgent as MAIN_AGENT

__all__ = ["MAIN_AGENT"]

# --- BEGIN generated metadata (scmlweb update_agents_repo.py) ---
ID = 21196
NAME = 'Yamashitaagent'
CLASS_NAME = 'YamashitaAgent'
VERSION = '3.11.7'
TEAM = 'Team 369'
AUTHOR = 'Masaki Yamashita'
MEMBERS = [{'name': 'Masaki Yamashita', 'institution': 'Kyoto University', 'country': 'Japan'}]
COUNTRY = 'Japan'
INSTITUTION = 'Kyoto University'
TAGS = []
USES_LLM = False
DESC = ''
METADATA = {
    'id': ID, 'name': NAME, 'class_name': CLASS_NAME,
    'version': VERSION, 'team': TEAM, 'author': AUTHOR,
    'members': MEMBERS, 'country': COUNTRY,
    'institution': INSTITUTION, 'tags': TAGS,
    'uses_llm': USES_LLM, 'description': DESC,
}
# --- END generated metadata ---
