"""SCML 2026 participant team_21127 (agent id 21127, class ShimijimiShijimi).

Generated by scmlweb/python/update_agents_repo.py.
"""
from .strategy import ShimijimiShijimi as MAIN_AGENT

__all__ = ["MAIN_AGENT"]

# --- BEGIN generated metadata (scmlweb update_agents_repo.py) ---
ID = 21127
NAME = 'ShimijimiShijimi'
CLASS_NAME = 'ShimijimiShijimi'
VERSION = '1'
TEAM = 'Team 376'
AUTHOR = 'Rinon Asanuma'
MEMBERS = [{'name': 'Rinon Asanuma', 'institution': None, 'country': 'Japan'}]
COUNTRY = 'Japan'
INSTITUTION = 'Tokyo University of Agriculture and Technology'
TAGS = ['Search Algorithms', 'Heuristic / Rule-based', 'Optimization']
USES_LLM = False
DESC = 'ShimijimiShijimi is a synchronous negotiating agent designed for the ANAC 2026 SCML Standard League. Its core strategy revolves around temporal partner partitioning and combinatorial offer matching to ensure stable factory utilization while mitigating supply chain risks. Rather than competing solely for same-day contracts, the agent divides its active negotiation partners into a strict 7:2:1 ratio: 70% of partners negotiate for immediate daily needs, 20% secure 40% of the projected needs for one step ahead, and 10% secure 40% of the needs for two steps ahead. For future contracts, the agent immediately targets the absolute best price, while current-day negotiations incorporate strategic pricing margins to maximize profitability. When evaluating incoming offers, the agent avoids greedy heuristics; instead, it generates a mathematical power-set of all current-day offers to find the exact combination of contracts that best matches its required volume within a specific threshold. Coupled with preemptive internal ledgers to track secured agreements instantly, this strategy prevents both severe component starvation and costly inventory overflow, ensuring robust performance in volatile markets.'
METADATA = {
    'id': ID, 'name': NAME, 'class_name': CLASS_NAME,
    'version': VERSION, 'team': TEAM, 'author': AUTHOR,
    'members': MEMBERS, 'country': COUNTRY,
    'institution': INSTITUTION, 'tags': TAGS,
    'uses_llm': USES_LLM, 'description': DESC,
}
# --- END generated metadata ---
