name: CI

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]

jobs:
  tests:
    name: "Python ${{ matrix.python-version }}"
    runs-on: "ubuntu-latest"
    env:
      USING_COVERAGE: '3.8'

    strategy:
      matrix:
        python-version: ["3.8.12", "3.9.10", "3.10.2"]

    steps:
      - uses: "actions/checkout@v2"
      - uses: "actions/setup-python@v1"
        with:
          python-version: "${{ matrix.python-version }}"
      - name: "Install dependencies"
        run: |
          set -xe
          python -VV
          python -m site
          python -m pip install --upgrade pip setuptools wheel pytest
          python -m pip install --upgrade  virtualenv
          python -m pip install -r requirements.txt
          yes | python -m pip uninstall negmas
          python -m pip install git+https://github.com/yasserfarouk/negmas.git
          yes | python -m pip uninstall scml
          python -m pip install git+https://github.com/yasserfarouk/scml.git
      - name: "Run pytest for ${{ matrix.python-version }}"
        run: "python -W ignore -m pytest tests"

  package:
    name: "Build & verify package"
    runs-on: "ubuntu-latest"

    steps:
      - uses: "actions/checkout@v2"
      - uses: "actions/setup-python@v1"
        with:
          python-version: "3.8"

      - name: "Install pep517 and twine"
        run: "python -m pip install --upgrade pip setuptools wheel pytest twine"
      - name: "Build package"
        run: "python setup.py sdist bdist_wheel"
      - name: "List result"
        run: "ls -l dist"
      - name: "Check long_description"
        run: "python -m twine check dist/*"
